### ISSUE TITLE
BUG in "send_file" and "send_from_directory"

### ISSUE THREAD

**Issue by baisk** [mitsuhiko/flask#1169]
L496 in helpers.py
If i use flask as a package instead of a module,  I want to expose a file which is not in package.
checks in send_from_directory will be passed because of rel path.  However, in send_file,  added abs folder, it occur an error.

**Comment by welshjf** [comment]
I've hit this problem too; perhaps I can clarify what's going on.

`send_from_directory` tests for existence based on the `safe_join` of `directory` and `filename`. So if `directory` is relative, this is relative to the current working directory of the process -- pretty unreliable. `send_file`, however, expands relative paths based on `current_app.root_path`, and does not have any existence check.

Thus, if the CWD and `root_path` do not match, `send_from_directory` may prematurely raise a 404 for files that do exist, or fail to do so for files that happen to exist in the CWD but not the `root_path`. In the second case, you get a 500 internal error when `os.path.getsize` or `getmtime` fail. Very inconsistent.

My suggestsions:
* If you must do an existence check and raise a 404, do it from `send_file` where the final path is known. This would fix the CWD issue and give a consistent error behavior for the two functions. Or at least enforce that `directory` is absolute in `send_from_directory`.
* The above is still subject to race conditions, so preferably don't do any inspection of the file, leaving the content-length and mtime to the code that actually sends it. At least in the case of x-sendfile on Apache it sounds like this should work: "Sets correct cache headers such as Etag and If-Modified-Since as if the file was statically served" (https://tn123.org/mod_xsendfile/). Unfortunately it would bypass the app's error handling in the event of a 404, but that's possible in any case due to the race condition or other problems like permissions.

**Comment by untitaker** [comment]
>send_from_directory tests for existence based on the safe_join of directory and filename. So if directory is relative, this is relative to the current working directory of the process -- pretty unreliable. 

Did you try latest master?

**Comment by untitaker** [comment]
Also I think the current errorhandling regarding raising `NotFound` is intentional -- `send_file` is used in situations where the app dev knows a particular file exists. E.g. it wouldn't help with debugging if the following code raises a 404:

   return send_file('robots.txt')

 OTOH I see `send_from_directory` as a function where the `filename` may originate from user input, therefore it's usually not a 500 if the to-be-sent file doesn't exist.

We should still take a look at the races though -- maybe just catch exceptions from the `send_file` invocation inside `send_from_directory` instead of doing own checks.

**Comment by untitaker** [comment]
Oh, and I'd like to document the errorhandling of these two functions too somewhere (if it's not already documented).

**Comment by welshjf** [comment]
I was using 0.10.1. You're right, this was fixed in #921. And the distinction you make between the functions makes sense, though I agree the docs could make it clearer. @baisk, does this fix your issue too?

**Comment by davidism** [comment]
@untitaker having trouble following this whole thread.  Is this just open because you want some more documentation?  It doesn't look like there's an actual problem.

**Comment by untitaker** [comment]
Agreed. Docs are a nice to have but I guess it isn't actually on any roadmap.

**Comment by jv1522** [comment]
I am unable to host the files using send_from_directory and send_file on linux machines.
