### ISSUE TITLE
New label 'good first bug'

### ISSUE THREAD

**Issue by jrm2k6** [mitsuhiko/flask#1233]
Sorry in advance if it is not the right place to open this kind of issue.
I think it would be nice to have issues labelled 'good first bug' for people wanting to contribute but not knowing how to start.

**Comment by untitaker** [comment]
@jrm2k6 Are you still interested in this?

**Comment by jrm2k6** [comment]
Hi,
Sorry, kinda busy at the moment and didn't have time to commit to it. Better assign it to someone else.

**Comment by ajgrover** [comment]
I also support this. One type of issue that would be useful to tag with this label is known bugs that have a clear fix - I often see issues that are proposing slight changes to the API (whether that is error handling, restructuring responses, etc.) and as a newcomer those are particularly hard to tackle because you don't know if the changes are even wanted in the first place.

Mentors would be nice as well but I'm not sure that you guys have the time/resources to spare to make that happen.

**Comment by untitaker** [comment]
Basically everything with a milestone is planned, if that's what you're looking for.

**Comment by keyanp** [comment]
Would be nice if some of the core contributors could tag some more issues. I'm trying to find a new issue to work on but the tracker is not well maintained. For some of the issues it is unclear whether anyone wants work to be done (#1317, #1304, #1257) and many others are just duplicates (#1251, #1356, #1333). Willing to work on something, get in touch.

**Comment by untitaker** [comment]
@keyanp Regarding the duplicates of https://github.com/pocoo/metaflask/issues/7, I leave them open because as soon as I close them, somebody else opens a new issue. Having a few open issues hopefully makes it clear to reporters that their bug is already known.

I'll leave comments on the other issues.

**Comment by keyanp** [comment]
@untitaker Thanks Markus. Im going to try tackling #1317. I'd say the 'good first bug' tag is less important than simply making it more clear which issues are actually looking for contributors (as you did for #1317) vs. those which are still being discussed.

**Comment by pythonui** [comment]
+1 for "good first bug"

**Comment by keyanp** [comment]
Now that the tag has been created I don't think this needs to be open anymore.

**Comment by untitaker** [comment]
I think so, but new issues have to be continuously tagged for this issue to stay resolved.

If anybody finds any issues that would deserve this label, please comment on that particular issue.
