### ISSUE TITLE
distribute_setup.py link for windows setup has gone bad 

### ISSUE THREAD

**Issue by tbarn** [mitsuhiko/flask#1322]
In http://flask.pocoo.org/docs/0.10/installation/#windows-easy-install the distribute_setup.py link looks like the domain owner didn't renew or lost the site so the script is not there. 

I looked elsewhere for a good script, not sure which one would be the best to think to. A lot of the sites that also host the script just look fishy but could be options.

**Comment by kierandarcy** [comment]
It looks like the documentation could do with being updated here. Since Python 2.7.9 and Python 3.4, pip is included by default. More up to date installation instructions can be found here: https://pip.pypa.io/en/latest/installing.html

In brief, the installation instructions (for `pip` and `distribute`) are to download https://bootstrap.pypa.io/get-pip.py, then run...
```
python getpip.py
```

**Comment by tbarn** [comment]
I am not using a windows environment so I don't really need it for myself right now, but I was mentoring at a hackathon and it caused a younger student to get confused so I just wanted to get the link fixed somehow. 

Great to see it is fixed in the development version! I forgot to check it.

**Comment by untitaker** [comment]
Closing this then
