### ISSUE TITLE
The server stops serving webpages after being deployed for more than a day

### ISSUE THREAD

**Issue by shubhamgoyal** [mitsuhiko/flask#1415]
I deployed a simple Flask web server to serve http://www.holmusk.com/ and it mysteriously stops serving pages after a few hours. There are no errors on the console. Can you help guide me towards what the possible issue might be?

**Comment by untitaker** [comment]
Don't use the built-in server for production.

**Comment by niothiel** [comment]
Check here for your options: http://flask.pocoo.org/docs/0.10/deploying/

**Comment by ThiefMaster** [comment]
FYI, you are running the dev server in debug mode with evalex enabled. Also, you are running it with root permissions. This means that **ANYONE was able to execute command as root on your machine!**

I used the [werkzeug debugger shell](http://www.holmusk.com/console) to kill the dev server to remove the risk a compromised machine poses to the internet (black hats tend to abuse them for attacks, bitcoin mining, spam, warez, and other unwanted things).

However, since it's impossible to know for sure if someone else also found out about it, you should assume the machine has already been compromised and reinstall it from scratch!
