### ISSUE TITLE
add automatic pep8 test in travis

### ISSUE THREAD

**Issue by Liuchang0812** [mitsuhiko/flask#1561]
It's very useful and easy to modify travis.yml。

**Comment by sils1297** [comment]
FWIW I'm developing a tool named coala which let's you use linters and write your own rules. It allows you to put in a very small config file, e.g.:

```
[python]
files = **/*.py
ignore = docs/**
bears = PEP8Bear, PyImportSortBear, PyUnusedCodeBear, PyLintBear
use_spaces = True
# The following yield false positives in PyLint, e.g. it doesn't understand some
# of the Flask magic.
pylint_disable = R0903, C0103, E1101
```

What's special about this is that you get one executable for all your code analytics (you could add a section for checking your RST files e.g. easily), you can use it in Gedit, Sublime, Atom or from the command line (JSON, interactive, custom format) and, most importantly, it can automatically apply fixes (we use autopep8, isort and autoflake for PEP8Bear, PyImportSortBear and PyUnusedCodeBear) so your initial time to get your code clean should be far shorter. Config is also less redundant because if you specify `line_length` in coala all Bears will pick that up (otherwise it's a bug ;)) so you don't have to specify it again for each tool.

(Bonus: if you want specific "rules" for your project you can easily write your own bears that reside in your repository. Want to check your commit messages? :)
Bonus 2: you get one unified way to mark issues in certain lines/ranges as false positives.
Bonus 3: we're working on a service that provides you PR comments but it's very alpha. But one day it will be ready.)

Of course coala is open source. coala-analyzer.org provides more info - or me.

**Comment by davidism** [comment]
continued in #1702
