### ISSUE TITLE
why command flask not found

### ISSUE THREAD

**Issue by quantwizard** [mitsuhiko/flask#1654]
I git clone and enter the flaskr folder, then run the following command in Bash:
flask --app=flaskr initdb

then I got error: command not found: flask

How do I setup flaskr in this case? Do I miss something?

**Comment by icedtea1** [comment]
pip install https://github.com/mitsuhiko/flask/tarball/master

then try again.

**Comment by quantwizard** [comment]
It works, thanks!

**Comment by helfgott** [comment]
Verify where you have installed flask:


    mortiz@florida:~/Documents/projects$ pip freeze |grep -i flask
    Flask==1.0.2
    mortiz@florida:~/Documents/projects$ pip2 freeze |grep -i flask
    Flask==1.0.2
    mortiz@florida:~/Documents/projects$ pip3 freeze |grep -i flask
    Flask==1.0.2
    Flask-CLI==0.4.0
    Flask-Jsonpify==1.5.0
    Flask-RESTful==0.3.6
    Flask-SQLAlchemy==2.3.2

Verify you are installing flask for your correct python version inside your virtual environment.

**Find out your python version "inside your (venv)"**

    mortiz@florida:~/Documents/projects/python/APIS/new_project_py_2_7$ which python
        /home/mortiz/Documents/projects/python/APIS/new_project_py_2_7/venv/bin/python

    (venv) mortiz@florida:~/Documents/projects/python/APIS/new_project_py_2_7$ python --version
    Python 3.5.3

**Installation of flask for python3**

    pip3 install flask
    #or
    python3 -m pip install flask

**Installation of flask for python2**

    pip2 install flask
    #or
    python2 -m pip install flask

**Installation of flask for default python (be careful if you are inside your (venv) or in your shell)**

    pip install flask
    python -m install flask

> Explanation

For people who run higher versions of Flask consider evaluating your environment as [explained here][1].

For me the problem was installing flask for python2 when the binary of my (venv) ran python3. 

  [1]: http://migueleonardortiz.com.ar/python/bash-flask-command-not-found-with-flask-1-0-2/1692

**Comment by davidism** [comment]
@helfgott  thanks for following up with this, but your really over-complicating things. The answer is "make sure you're in an active virtualenv, then do `pip install flask`." Within a virtualenv, `pip` and `python` point to the correct version, whereas with the numbered ones you always have a chance you'll use the wrong one.
